JOB_STATUS_QUEUED = "queued"
JOB_STATUS_PROCESSING = "processing"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"
JOB_STATUS_EXPIRED = "expired"

JOB_STATUSES = {
    JOB_STATUS_QUEUED,
    JOB_STATUS_PROCESSING,
    JOB_STATUS_COMPLETED,
    JOB_STATUS_FAILED,
    JOB_STATUS_EXPIRED,
}

STAGE_UPLOADING = "uploading"
STAGE_EXTRACTING_TEXT = "extracting_text"
STAGE_PARSING = "parsing"
STAGE_GENERATING_EXPLANATION = "generating_explanation"
STAGE_FINALIZING = "finalizing"
STAGE_DONE = "done"
STAGE_FAILED = "failed"

JOB_STAGES = {
    STAGE_UPLOADING,
    STAGE_EXTRACTING_TEXT,
    STAGE_PARSING,
    STAGE_GENERATING_EXPLANATION,
    STAGE_FINALIZING,
    STAGE_DONE,
    STAGE_FAILED,
}

DEFAULT_PROGRESS_BY_STAGE = {
    STAGE_UPLOADING: 5,
    STAGE_EXTRACTING_TEXT: 25,
    STAGE_PARSING: 45,
    STAGE_GENERATING_EXPLANATION: 70,
    STAGE_FINALIZING: 90,
    STAGE_DONE: 100,
    STAGE_FAILED: 100,
}
